# Generated by Django 4.1 on 2022-08-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_role'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.courses'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('profile_pics', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('address', models.TextField()),
                ('level', models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1', 'HND1'), ('HND2', 'HND2')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.courses')),
                ('session_year_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session_year', to='accounts.sessionyearmodel')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ('created_at',),
            },
        ),
    ]
