# Generated by Django 4.1 on 2022-08-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_finance_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='school_fees',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='course',
        ),
        migrations.AddField(
            model_name='finance',
            name='name',
            field=models.CharField(default='School Fees', max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.finance'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='other_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
