# Generated by Django 4.1 on 2022-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_school_fees_finance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='name',
            field=models.CharField(default='School Feesst', max_length=250),
        ),
    ]
