# Generated by Django 4.1 on 2022-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_student_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fees',
        ),
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.ManyToManyField(related_name='student_fees', to='finance.finance'),
        ),
    ]
