# Generated by Django 4.1 on 2022-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENTS', 'Student'), ('TEACHER', 'Teacher')], default=('ADMIN', 'Admin'), max_length=20),
        ),
    ]
